---
- name: Check if CodeIt repo is already configured.
  ansible.builtin.stat:
    path: "{{ codeit_repo_file_path }}"
  register: codeit_repo_file_result

- name: Import CodeIT GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ codeit_repo_gpg_key_url }}"
  when: not codeit_repo_file_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add CodeIT yum repository.
  yum_repository:
    name: CodeIT
    description: CodeIT repo
    file: '{{ codeit_repo_file_name }}'
    baseurl: '{{ codeit_repo_file_base_url }} '
    gpgcheck: yes
    gpgkey: "{{ codeit_repo_gpg_key_url }}"
    enabled: yes
  when: not codeit_repo_file_result.stat.exists
